/* DO NOT EDIT THIS FILE - it is machine generated */
#include "jni.h"
/* Header for class util_ScriptUtil */

#ifndef _Included_util_ScriptUtil
#define _Included_util_ScriptUtil
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     util_ScriptUtil
 * Method:    keyPress
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_util_ScriptUtil_keyPress
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     util_ScriptUtil
 * Method:    mouseClick
 * Signature: (III)V
 */
JNIEXPORT void JNICALL Java_util_ScriptUtil_mouseClick
  (JNIEnv *, jclass, jint, jint, jint);

/*
 * Class:     util_ScriptUtil
 * Method:    getPosition
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_util_ScriptUtil_getPosition
  (JNIEnv *, jclass, jint);

/*
 * Class:     util_ScriptUtil
 * Method:    getHwnd
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_util_ScriptUtil_getHwnd
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
